CREATE TABLE IF NOT EXISTS public.medical_checkup (
    id BIGSERIAL PRIMARY KEY,
    year INTEGER,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    gender VARCHAR(15),
    weight DOUBLE PRECISION,
    height DOUBLE PRECISION,
    sugar DOUBLE PRECISION,
    bun DOUBLE PRECISION,
    creatinine DOUBLE PRECISION,
    egrf DOUBLE PRECISION,
    cholesterol DOUBLE PRECISION,
    triglycerides DOUBLE PRECISION,
    uric_acid DOUBLE PRECISION,
    total_protein DOUBLE PRECISION,
    albumin DOUBLE PRECISION,
    hdl_c DOUBLE PRECISION,
    ldl_c DOUBLE PRECISION,
    alk_phos DOUBLE PRECISION,
    sgot DOUBLE PRECISION,
    sgpt DOUBLE PRECISION,
    hbs_ag VARCHAR(20),
    wbc DOUBLE PRECISION,
    rbc_m DOUBLE PRECISION,
    hgb_m DOUBLE PRECISION,
    hct_m DOUBLE PRECISION,
    platelets DOUBLE PRECISION,
    neu DOUBLE PRECISION,
    lymp DOUBLE PRECISION,
    mono DOUBLE PRECISION,
    eos DOUBLE PRECISION,
    baso DOUBLE PRECISION,
    specific_gravity DOUBLE PRECISION,
    ph DOUBLE PRECISION,
    urine_exam VARCHAR(20),
    chest_x_ray VARCHAR(20)
);
